23 birthday check signup
davidtayloryangg/GroundBnB pull request #25
Opened 2022-12-08 01:55 UTC by uityh

Firebase functions call signup routes for both email+password signup and google signup. Still need to do validation of params on frontend and backend. Just wanted to do pr just to get the cors stuff in main

2022-12-11 22:52 UTC, LDomadia commented
Looks like it's working! I also testing with an email that already exists, and it does catch the error. But note for the future if we have time, we can make the error message look nicer, so it doesn't say "Firebase Error". Or it can be done in this PR if you have time.
<img width="1371" alt="Screen Shot 2022-12-11 at 5 50 19 PM" src="https://user-images.githubusercontent.com/62802533/206933581-7debceee-b8bf-4a47-a450-c43fb06c3cc3.png">

2022-12-12 01:45 UTC, LDomadia approved these changes

2022-12-13 02:40 UTC, RonnieArvanites requested changes
@uityh Can you display different messages when the user enters the wrong password or if the user enters an email that doesn't exist? Right now it says FirebaseError in the alert. Maybe when the user enters the wrong password or email just say "Either the email or password is incorrect".

2022-12-13 03:11 UTC, RonnieArvanites approved these changes

2022-12-13 03:12 UTC, merged