Added home page
davidtayloryangg/GroundBnB pull request #32
Opened 2022-12-13 03:04 UTC by RonnieArvanites

**Summary**
- Added home page with listings with pagination
- Added filtering button to filter listings by:
              - Rating: High to Low
              - Rating: Low to High
              - Price: High to Low
              - Price: Low to high
- Added global file for types

This is what the home page looks like. Some images are not displaying because they are messed up in firebase storage and I am not sure how to fix them.
<img width="1440" alt="HomePage" src="https://user-images.githubusercontent.com/33349950/207216122-90c25d6d-443a-4c53-9856-f5c80334f998.png">

2022-12-14 20:56 UTC, uityh requested changes
Looks really good! Only thing is that tota11y complains about it needing an h1 tag. So you might need to add that in and change the h6 tags to h2.
![totally](https://user-images.githubusercontent.com/20544092/207711943-733c4be6-a116-4abe-99ae-055d1d1b30cd.png)

2022-12-14 22:26 UTC, LDomadia commented
Looks good! One comment though: For the Queens listing where the images aren't showing up, should we put an "Image not Found" just in case certain images are causing errors?

2022-12-14 22:27 UTC, LDomadia approved these changes

2022-12-15 02:13 UTC, RonnieArvanites commented
> Looks really good! Only thing is that tota11y complains about it needing an h1 tag. So you might need to add that in and change the h6 tags to h2. ![totally](https://user-images.githubusercontent.com/20544092/207711943-733c4be6-a116-4abe-99ae-055d1d1b30cd.png) @uityh I fixed the tota11y errors.

2022-12-15 02:21 UTC, uityh approved these changes

2022-12-15 02:22 UTC, merged